name: Generate RSS

on:
  schedule:
    - cron: '0 */2 * * *' # 每2小时运行一次
  workflow_dispatch: # 允许在页面上手动点击运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 feedgen

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push XML
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add wenxuecity.xml
          git commit -m "Update wenxuecity RSS" || exit 0
          git push
